# [dev]
#   command = "yarn start"
#   publish = "dist"
#   port = 8080 

[build]
  command = "yarn build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/data/*.json"]
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
